export const CATEGORY_META = Object.freeze({
  state: Object.freeze({ label: 'Державність', accent: '#d69b0e' }),
  culture: Object.freeze({ label: 'Культура', accent: '#e65349' }),
  science: Object.freeze({ label: 'Наука', accent: '#338dce' }),
  society: Object.freeze({ label: 'Суспільство', accent: '#3c6d43' }),
  resistance: Object.freeze({ label: 'Боротьба', accent: '#276eaa' }),
});

// difficulty: 1 — загальновідомі події, 2 — шкільна програма, 3 — для знавців.
// Каталог упорядковано хронологічно; події з однаковим роком підтримуються рушієм.
export const EVENTS = Object.freeze([
  // ——— Княжа доба ———
  { id: 'askold-campaign', year: 860, title: 'Похід Аскольда на Константинополь', category: 'state', difficulty: 3, description: 'Флот київського князя Аскольда вперше з’явився під стінами столиці Візантії.' },
  { id: 'oleh-unites-kyiv', year: 882, title: 'Олег об’єднав Новгород і Київ', category: 'state', difficulty: 2, description: 'Князь Олег захопив Київ і зробив його столицею об’єднаної Русі.' },
  { id: 'oleh-tsargorod', year: 907, title: 'Похід Олега на Царгород', category: 'state', difficulty: 3, description: 'За літописом, Олег прибив щит на воротах Константинополя й здобув вигідну угоду.' },
  { id: 'oleh-byzantium-treaty', year: 911, title: 'Договір Олега з Візантією', category: 'state', difficulty: 3, description: 'Київський князь Олег уклав вигідний торговельний договір із Константинополем.' },
  { id: 'ihor-campaign', year: 941, title: 'Похід Ігоря на Візантію', category: 'state', difficulty: 3, description: 'Флот князя Ігоря був спалений «грецьким вогнем» у поході на Константинополь.' },
  { id: 'drevlian-uprising', year: 945, title: 'Повстання древлян', category: 'resistance', difficulty: 2, description: 'Древляни повстали проти повторного збору данини та вбили князя Ігоря.' },
  { id: 'olha-reforms', year: 947, title: 'Реформи княгині Ольги', category: 'state', difficulty: 3, description: 'Ольга впорядкувала збір данини, запровадивши уроки й погости.' },
  { id: 'olha-constantinople', year: 957, title: 'Візит Ольги до Константинополя', category: 'state', difficulty: 3, description: 'Київська княгиня відвідала візантійського імператора й прийняла хрещення.' },
  { id: 'khazars-defeat', year: 965, title: 'Розгром Хозарського каганату', category: 'state', difficulty: 2, description: 'Князь Святослав розбив хозарів і зруйнував їхню столицю Ітіль.' },
  { id: 'sviatoslav-death', year: 972, title: 'Загибель князя Святослава', category: 'state', difficulty: 2, description: 'Печеніги вбили князя-воїна біля дніпрових порогів, коли він повертався з Болгарії.' },
  { id: 'volodymyr-reign', year: 980, title: 'Володимир Великий очолив Русь', category: 'state', difficulty: 2, description: 'Після боротьби з братами Володимир Святославич утвердився на київському престолі.' },
  { id: 'baptism-of-rus', year: 988, title: 'Хрещення Русі', category: 'state', difficulty: 1, description: 'Князь Володимир запровадив християнство як релігію Київської Русі.' },
  { id: 'desiatynna-church', year: 996, title: 'Освячення Десятинної церкви', category: 'culture', difficulty: 2, description: 'У Києві завершили першу муровану церкву Русі, на яку князь віддав десятину доходів.' },
  { id: 'borys-hlib', year: 1015, title: 'Загибель князів Бориса і Гліба', category: 'society', difficulty: 3, description: 'Сини Володимира, вбиті у міжусобиці, стали першими святими Русі.' },
  { id: 'yaroslav-the-wise', year: 1019, title: 'Початок правління Ярослава Мудрого', category: 'state', difficulty: 2, description: 'Князь, за якого Русь досягла розквіту, утвердився на київському престолі.' },
  { id: 'pechenihy-defeat', year: 1036, title: 'Розгром печенігів під Києвом', category: 'resistance', difficulty: 3, description: 'Ярослав Мудрий завдав кочовикам поразки, після якої їхні набіги припинилися.' },
  { id: 'sophia-cathedral', year: 1037, title: 'Закладення Софійського собору', category: 'culture', difficulty: 2, description: 'У Києві почали зводити головний храм Русі зі всесвітньо відомими мозаїками.' },
  { id: 'kyiv-pechersk-lavra', year: 1051, title: 'Заснування Києво-Печерського монастиря', category: 'culture', difficulty: 2, description: 'Чернеча обитель у Києві стала одним із головних духовних і культурних центрів Русі.' },
  { id: 'anna-yaroslavna', year: 1051, title: 'Анна Ярославна — королева Франції', category: 'state', difficulty: 2, description: 'Донька Ярослава Мудрого взяла шлюб із французьким королем Генріхом I.' },
  { id: 'yaroslav-death', year: 1054, title: 'Смерть Ярослава Мудрого', category: 'state', difficulty: 2, description: 'Після смерті князя Русь була поділена між його синами за заповітом.' },
  { id: 'dormition-cathedral', year: 1073, title: 'Закладення Успенського собору Лаври', category: 'culture', difficulty: 3, description: 'У Печерському монастирі почали будувати головний собор, взірець для храмів Русі.' },
  { id: 'liubech-congress', year: 1097, title: 'Любецький з’їзд князів', category: 'state', difficulty: 2, description: 'Князі домовилися «кожен хай тримає отчину свою», закріпивши поділ Русі.' },
  { id: 'cumans-campaign-1103', year: 1103, title: 'Переможний похід на половців', category: 'resistance', difficulty: 3, description: 'Об’єднане військо князів на чолі з Мономахом розбило половців у степу.' },
  { id: 'mykhailivskyi-sobor', year: 1108, title: 'Михайлівський Золотоверхий собор', category: 'culture', difficulty: 3, description: 'У Києві звели собор із золоченими банями, що дав назву монастирю.' },
  { id: 'primary-chronicle', year: 1113, title: 'Завершення «Повісті минулих літ»', category: 'culture', difficulty: 3, description: 'Літописець Нестор упорядкував головне джерело з історії Київської Русі.' },
  { id: 'monomakh-kyiv', year: 1113, title: 'Володимир Мономах очолив Київ', category: 'state', difficulty: 2, description: 'Покликаний киянами князь припинив міжусобиці й відновив єдність Русі.' },
  { id: 'bogoliubsky-sack', year: 1169, title: 'Розорення Києва Боголюбським', category: 'state', difficulty: 3, description: 'Військо володимиро-суздальського князя захопило й пограбувало Київ.' },
  { id: 'ihor-polovtsi', year: 1185, title: 'Похід Ігоря Сіверського на половців', category: 'culture', difficulty: 2, description: 'Невдалий похід новгород-сіверського князя був оспіваний у «Слові о полку Ігоревім».' },
  { id: 'first-mention-ukraine', year: 1187, title: 'Перша згадка назви «Україна»', category: 'state', difficulty: 3, description: 'Київський літопис ужив назву «Україна», описуючи смерть переяславського князя.' },
  { id: 'halych-volyn-union', year: 1199, title: 'Об’єднання Галичини й Волині', category: 'state', difficulty: 2, description: 'Князь Роман Мстиславич створив могутнє Галицько-Волинське князівство.' },
  { id: 'kalka-battle', year: 1223, title: 'Битва на річці Калці', category: 'resistance', difficulty: 1, description: 'Руські князі та половці зазнали першої нищівної поразки від монголів.' },
  { id: 'danylo-halych', year: 1238, title: 'Данило Романович утвердився в Галичі', category: 'state', difficulty: 3, description: 'Майбутній король остаточно повернув собі батьківський галицький престол.' },
  { id: 'mongol-sack-of-kyiv', year: 1240, title: 'Зруйнування Києва військом Батия', category: 'resistance', difficulty: 2, description: 'Після тривалої облоги монгольське військо здобуло й спустошило столицю Русі.' },
  { id: 'yaroslav-battle-1245', year: 1245, title: 'Битва під Ярославом', category: 'resistance', difficulty: 3, description: 'Данило Галицький розгромив угорсько-польське військо та бунтівних бояр.' },
  { id: 'danylo-coronation', year: 1253, title: 'Коронація Данила Галицького', category: 'state', difficulty: 2, description: 'Галицько-волинський князь прийняв королівську корону від папського легата в Дорогичині.' },
  { id: 'first-mention-lviv', year: 1256, title: 'Перша письмова згадка про Львів', category: 'society', difficulty: 2, description: 'Місто Лева вперше з’явилося в літописній розповіді про пожежу в Холмі.' },
  { id: 'halych-metropolis', year: 1303, title: 'Утворення Галицької митрополії', category: 'culture', difficulty: 3, description: 'Константинополь визнав окрему митрополію для галицько-волинських земель.' },
  { id: 'romanovychi-end', year: 1340, title: 'Кінець династії Романовичів', category: 'state', difficulty: 3, description: 'Після отруєння князя Юрія II за галицько-волинську спадщину почалася боротьба сусідів.' },
  { id: 'casimir-halychyna', year: 1349, title: 'Похід Казимира III на Галичину', category: 'state', difficulty: 3, description: 'Польський король захопив Львів і почав приєднання галицьких земель.' },
  { id: 'syni-vody', year: 1362, title: 'Битва на Синіх Водах', category: 'resistance', difficulty: 2, description: 'Литовсько-руське військо Ольгерда розбило ординців і звільнило Поділля та Київщину.' },
  { id: 'krevo-union', year: 1385, title: 'Кревська унія', category: 'state', difficulty: 2, description: 'Литва та Польща уклали династичний союз, що змінив долю українських земель.' },
  { id: 'halychyna-poland', year: 1387, title: 'Галичина остаточно під Польщею', category: 'state', difficulty: 3, description: 'Польське королівство закріпило за собою галицькі землі майже на чотири століття.' },
  { id: 'grunwald-battle', year: 1410, title: 'Грюнвальдська битва', category: 'resistance', difficulty: 2, description: 'Українські хоругви в складі союзного війська допомогли розгромити Тевтонський орден.' },
  { id: 'crimean-khanate', year: 1449, title: 'Утворення Кримського ханства', category: 'state', difficulty: 3, description: 'Хаджі-Гірей заснував незалежну від Орди державу кримських татар.' },
  { id: 'kyiv-principality-end', year: 1471, title: 'Ліквідація Київського князівства', category: 'state', difficulty: 3, description: 'Литва перетворила удільне Київське князівство на звичайне воєводство.' },
  { id: 'mengli-sack', year: 1482, title: 'Спустошення Києва Менглі-Гіреєм', category: 'resistance', difficulty: 3, description: 'Кримський хан на прохання Москви зруйнував Київ і спалив Печерський монастир.' },
  { id: 'drohobych-book', year: 1483, title: 'Перша друкована книга українця', category: 'science', difficulty: 3, description: 'У Римі вийшла «Прогностична оцінка» ректора Болонського університету Юрія Дрогобича.' },
  { id: 'first-cossacks-mention', year: 1489, title: 'Перша письмова згадка про козаків', category: 'society', difficulty: 2, description: 'Польська хроніка вперше згадала українських козаків у степових походах.' },
  { id: 'kyiv-magdeburg', year: 1494, title: 'Магдебурзьке право для Києва', category: 'society', difficulty: 3, description: 'Київ дістав самоврядування за німецьким міським правом.' },
  { id: 'orsha-battle', year: 1514, title: 'Битва під Оршею', category: 'resistance', difficulty: 3, description: 'Військо Костянтина Острозького розгромило переважаючі московські сили.' },
  { id: 'lithuanian-statute', year: 1529, title: 'Перший Литовський статут', category: 'state', difficulty: 3, description: 'Кодекс законів Великого князівства Литовського діяв і на українських землях.' },

  // ——— Козацька доба ———
  { id: 'khortytsia-sich', year: 1556, title: 'Перша Запорозька Січ на Хортиці', category: 'resistance', difficulty: 2, description: 'Дмитро Вишневецький звів на острові Хортиця укріплення, що дало початок Січі.' },
  { id: 'peresopnytsia-gospel', year: 1561, title: 'Завершення Пересопницького Євангелія', category: 'culture', difficulty: 3, description: 'Було завершено визначну рукописну пам’ятку староукраїнської літературної мови.' },
  { id: 'lublin-union', year: 1569, title: 'Люблінська унія', category: 'state', difficulty: 2, description: 'Польща й Литва об’єдналися в Річ Посполиту; українські землі перейшли до Корони.' },
  { id: 'registered-cossacks', year: 1572, title: 'Створення реєстрового козацтва', category: 'state', difficulty: 3, description: 'Король уперше взяв частину козаків на державну службу за платню.' },
  { id: 'apostol-lviv', year: 1574, title: '«Апостол» — перша друкована книга в Україні', category: 'culture', difficulty: 2, description: 'Іван Федоров видав у Львові першу датовану друковану книгу на українських землях.' },
  { id: 'ostroh-academy', year: 1576, title: 'Заснування Острозької академії', category: 'science', difficulty: 2, description: 'В Острозі постала одна з найдавніших вищих шкіл у Східній Європі.' },
  { id: 'ostroh-bible', year: 1581, title: 'Друк Острозької Біблії', category: 'culture', difficulty: 3, description: 'Іван Федоров надрукував перше повне видання Біблії церковнослов’янською мовою.' },
  { id: 'lviv-brotherhood-school', year: 1586, title: 'Львівська братська школа', category: 'science', difficulty: 3, description: 'Успенське братство відкрило школу, що стала зразком для братських шкіл України.' },
  { id: 'kosynsky-uprising', year: 1591, title: 'Повстання Криштофа Косинського', category: 'resistance', difficulty: 3, description: 'Перше велике козацьке повстання охопило Київщину, Волинь і Поділля.' },
  { id: 'nalyvaiko-uprising', year: 1594, title: 'Повстання Северина Наливайка', category: 'resistance', difficulty: 3, description: 'Козацько-селянське повстання прокотилося українськими та білоруськими землями.' },
  { id: 'brest-union', year: 1596, title: 'Берестейська церковна унія', category: 'state', difficulty: 2, description: 'Частина православних єпископів визнала владу Папи — постала унійна церква.' },
  { id: 'kyiv-brotherhood-school', year: 1615, title: 'Київська братська школа', category: 'science', difficulty: 3, description: 'На Подолі відкрили школу, з якої згодом виросла Києво-Могилянська академія.' },
  { id: 'kafa-campaign', year: 1616, title: 'Похід Сагайдачного на Кафу', category: 'resistance', difficulty: 3, description: 'Козаки здобули головний невільницький ринок Криму та звільнили бранців.' },
  { id: 'moscow-campaign-1618', year: 1618, title: 'Похід Сагайдачного на Москву', category: 'resistance', difficulty: 3, description: 'Козацьке військо дійшло до стін Москви, змусивши царя до перемир’я.' },
  { id: 'hierarchy-restored', year: 1620, title: 'Відновлення православної ієрархії', category: 'culture', difficulty: 3, description: 'Єрусалимський патріарх Феофан висвятив нових православних єпископів у Києві.' },
  { id: 'khotyn-battle', year: 1621, title: 'Хотинська битва', category: 'resistance', difficulty: 2, description: 'Козаки Петра Сагайдачного разом із польським військом зупинили османський наступ.' },
  { id: 'triasylo-uprising', year: 1630, title: 'Повстання Тараса Трясила', category: 'resistance', difficulty: 3, description: 'Козаки завдали полякам відчутних втрат у «Тарасовій ночі» під Переяславом.' },
  { id: 'kyiv-mohyla-collegium', year: 1632, title: 'Створення Києво-Могилянської колегії', category: 'science', difficulty: 2, description: 'Петро Могила об’єднав київські школи в заклад, що став академією світового рівня.' },
  { id: 'pavliuk-uprising', year: 1637, title: 'Повстання Павлюка', category: 'resistance', difficulty: 3, description: 'Чергове козацьке повстання завершилося поразкою та «Ординацією» проти козаків.' },
  { id: 'zhovti-vody', year: 1648, title: 'Битва під Жовтими Водами', category: 'resistance', difficulty: 2, description: 'Козацьке військо здобуло першу велику перемогу на початку повстання Богдана Хмельницького.' },
  { id: 'korsun-battle', year: 1648, title: 'Битва під Корсунем', category: 'resistance', difficulty: 3, description: 'Хмельницький ущент розбив коронне військо й полонив обох гетьманів Речі Посполитої.' },
  { id: 'zboriv-treaty', year: 1649, title: 'Зборівський договір', category: 'state', difficulty: 2, description: 'Перша угода повсталої Гетьманщини з Річчю Посполитою визнала козацьку автономію.' },
  { id: 'berestechko-battle', year: 1651, title: 'Битва під Берестечком', category: 'resistance', difficulty: 2, description: 'Козацьке військо зазнало тяжкої поразки в одній із найбільших битв XVII століття.' },
  { id: 'batih-battle', year: 1652, title: 'Битва під Батогом', category: 'resistance', difficulty: 3, description: 'Хмельницький блискуче розгромив польське військо на Поділлі.' },
  { id: 'pereiaslav-council', year: 1654, title: 'Переяславська рада', category: 'state', difficulty: 1, description: 'Козацька старшина на чолі з Хмельницьким уклала союзну угоду з московським царем.' },
  { id: 'kharkiv-founded', year: 1654, title: 'Заснування Харкова', category: 'society', difficulty: 3, description: 'Переселенці з Правобережжя заклали фортецю, що дала початок місту.' },
  { id: 'khmelnytsky-death', year: 1657, title: 'Смерть Богдана Хмельницького', category: 'state', difficulty: 2, description: 'Після смерті гетьмана Україна поринула в добу Руїни.' },
  { id: 'hadiach-treaty', year: 1658, title: 'Гадяцький договір', category: 'state', difficulty: 3, description: 'Іван Виговський домовився про Велике князівство Руське в складі Речі Посполитої.' },
  { id: 'konotop-battle', year: 1659, title: 'Конотопська битва', category: 'resistance', difficulty: 2, description: 'Військо Виговського з татарами розгромило московську кінноту під Конотопом.' },
  { id: 'lviv-university', year: 1661, title: 'Заснування Львівського університету', category: 'science', difficulty: 2, description: 'Єзуїтська колегія у Львові дістала права академії — найстаршого університету України.' },
  { id: 'chorna-rada', year: 1663, title: 'Чорна рада в Ніжині', category: 'state', difficulty: 3, description: 'Бурхлива козацька рада обрала гетьманом Івана Брюховецького й розколола Україну.' },
  { id: 'andrusovo-truce', year: 1667, title: 'Андрусівське перемир’я', category: 'state', difficulty: 2, description: 'Польща й Москва поділили Україну по Дніпру без участі козаків.' },
  { id: 'eternal-peace-1686', year: 1686, title: '«Вічний мир» і доля митрополії', category: 'state', difficulty: 3, description: 'Поділ України закріпили остаточно, а Київську митрополію підпорядкували Москві.' },
  { id: 'mazepa-hetman', year: 1687, title: 'Іван Мазепа став гетьманом', category: 'state', difficulty: 2, description: 'Почалося двадцятилітнє гетьманування мецената, що прагнув унезалежнити Україну.' },
  { id: 'baturyn-destruction', year: 1708, title: 'Зруйнування Батурина', category: 'resistance', difficulty: 2, description: 'Московське військо Меншикова знищило гетьманську столицю та її мешканців.' },
  { id: 'poltava-battle', year: 1709, title: 'Полтавська битва', category: 'resistance', difficulty: 1, description: 'Під Полтавою військо Петра I розбило шведську армію та козаків Івана Мазепи.' },
  { id: 'orlyk-constitution', year: 1710, title: 'Конституція Пилипа Орлика', category: 'state', difficulty: 2, description: 'Козацька старшина ухвалила документ про права, обов’язки та устрій майбутньої держави.' },
  { id: 'skovoroda-birth', year: 1722, title: 'Народження Григорія Сковороди', category: 'culture', difficulty: 3, description: 'На Полтавщині народився мандрівний філософ, якого «світ ловив, та не спіймав».' },
  { id: 'nova-sich', year: 1734, title: 'Заснування Нової Січі', category: 'state', difficulty: 3, description: 'Запорожці повернулися з-під протекції Криму та заклали останню Січ на Підпільній.' },
  { id: 'rozumovsky-hetman', year: 1750, title: 'Кирило Розумовський — останній гетьман', category: 'state', difficulty: 3, description: 'У Глухові обрали останнього гетьмана Лівобережної України.' },
  { id: 'hetmanate-abolished', year: 1764, title: 'Скасування гетьманства', category: 'state', difficulty: 2, description: 'Катерина II ліквідувала інститут гетьмана та створила Малоросійську колегію.' },
  { id: 'koliivshchyna', year: 1768, title: 'Коліївщина', category: 'resistance', difficulty: 2, description: 'Гайдамацьке повстання Залізняка й Гонти охопило Правобережну Україну.' },
  { id: 'halychyna-austria', year: 1772, title: 'Галичина під владою Австрії', category: 'state', difficulty: 2, description: 'Після першого поділу Речі Посполитої західноукраїнські землі відійшли Габсбургам.' },
  { id: 'sich-liquidation', year: 1775, title: 'Зруйнування Запорозької Січі', category: 'state', difficulty: 2, description: 'За наказом Катерини II російські війська знищили останню Запорозьку Січ.' },
  { id: 'katerynoslav-founded', year: 1776, title: 'Заснування Катеринослава', category: 'society', difficulty: 3, description: 'На Дніпрі заклали губернське місто — нинішній Дніпро.' },
  { id: 'crimea-annexation-1783', year: 1783, title: 'Анексія Кримського ханства Росією', category: 'state', difficulty: 2, description: 'Російська імперія ліквідувала державу кримських татар і приєднала півострів.' },
  { id: 'kuban-resettlement', year: 1792, title: 'Переселення чорноморців на Кубань', category: 'society', difficulty: 3, description: 'Колишні запорожці отримали землі на Кубані й заснували там нові станиці.' },
  { id: 'odesa-founded', year: 1794, title: 'Заснування Одеси', category: 'society', difficulty: 2, description: 'На місці фортеці Хаджибей почали будувати головний порт Чорного моря.' },
  { id: 'eneida', year: 1798, title: 'Перше видання «Енеїди»', category: 'culture', difficulty: 2, description: 'Поема Івана Котляревського започаткувала нову українську літературу.' },

  // ——— Імперська доба ———
  { id: 'kharkiv-university', year: 1805, title: 'Відкриття Харківського університету', category: 'science', difficulty: 2, description: 'У Харкові почав діяти перший університет на підросійській Україні.' },
  { id: 'shevchenko-birth', year: 1814, title: 'Народження Тараса Шевченка', category: 'culture', difficulty: 1, description: 'У селі Моринці народився майбутній національний поет України.' },
  { id: 'pavlovsky-grammar', year: 1818, title: 'Перша граматика української мови', category: 'science', difficulty: 3, description: 'Олексій Павловський видав граматику живої народної української мови.' },
  { id: 'natalka-poltavka', year: 1819, title: 'Прем’єра «Наталки Полтавки»', category: 'culture', difficulty: 3, description: 'У Полтаві вперше зіграли п’єсу Котляревського — початок українського театру.' },
  { id: 'dikanka-evenings', year: 1831, title: '«Вечори на хуторі біля Диканьки»', category: 'culture', difficulty: 3, description: 'Микола Гоголь прославив українське село у своїй першій збірці повістей.' },
  { id: 'kyiv-university', year: 1834, title: 'Заснування Київського університету', category: 'science', difficulty: 2, description: 'У Києві відкрили університет Святого Володимира — нинішній університет Шевченка.' },
  { id: 'rusalka-dnistrova', year: 1837, title: '«Русалка Дністровая»', category: 'culture', difficulty: 3, description: 'Руська трійця видала першу книжку народною мовою на західноукраїнських землях.' },
  { id: 'kobzar', year: 1840, title: 'Вихід першого «Кобзаря»', category: 'culture', difficulty: 1, description: 'У Петербурзі надрукували першу збірку поезій Тараса Шевченка.' },
  { id: 'zapovit', year: 1845, title: 'Шевченко написав «Заповіт»', category: 'culture', difficulty: 2, description: 'Хворий поет у Переяславі створив вірш, що став національним гімном-молитвою.' },
  { id: 'cyril-methodius', year: 1846, title: 'Кирило-Мефодіївське братство', category: 'society', difficulty: 2, description: 'Київські інтелігенти таємно обговорювали майбутнє слов’янської федерації та волі.' },
  { id: 'holovna-ruska-rada', year: 1848, title: 'Головна руська рада у Львові', category: 'society', difficulty: 2, description: 'Під час «весни народів» галицькі українці створили першу політичну організацію.' },
  { id: 'serfdom-abolished', year: 1861, title: 'Скасування кріпацтва', category: 'society', difficulty: 1, description: 'Селянська реформа звільнила мільйони українських селян від кріпацької залежності.' },
  { id: 'lviv-railway', year: 1861, title: 'Перша залізниця до Львова', category: 'science', difficulty: 3, description: 'До Львова прибув перший потяг — почалася доба залізниць на українських землях.' },
  { id: 'valuev-circular', year: 1863, title: 'Валуєвський циркуляр', category: 'society', difficulty: 3, description: 'Російський міністр таємно заборонив друк релігійних та освітніх книжок українською.' },
  { id: 'anthem-music', year: 1863, title: 'Музика гімну «Ще не вмерла Україна»', category: 'culture', difficulty: 2, description: 'Михайло Вербицький поклав на музику вірш Павла Чубинського.' },
  { id: 'odesa-university', year: 1865, title: 'Новоросійський університет в Одесі', category: 'science', difficulty: 3, description: 'Одеса дістала власний університет — майбутній університет Мечникова.' },
  { id: 'prosvita', year: 1868, title: 'Заснування товариства «Просвіта»', category: 'society', difficulty: 2, description: 'У Львові створили товариство для поширення освіти й української культури.' },
  { id: 'yuzivka-founded', year: 1869, title: 'Заснування Юзівки', category: 'society', difficulty: 3, description: 'Валлієць Джон Юз збудував металургійний завод — початок Донецька.' },
  { id: 'shevchenko-society', year: 1873, title: 'Створення Товариства імені Шевченка', category: 'science', difficulty: 3, description: 'У Львові постало товариство, що згодом стало неофіційною українською академією наук.' },
  { id: 'chernivtsi-university', year: 1875, title: 'Чернівецький університет', category: 'science', difficulty: 3, description: 'Австрійська влада відкрила університет у столиці Буковини.' },
  { id: 'ems-ukaz', year: 1876, title: 'Емський указ', category: 'society', difficulty: 2, description: 'Олександр II заборонив друк і ввезення книжок українською мовою.' },
  { id: 'hromada-geneva', year: 1878, title: '«Громада» Драгоманова в Женеві', category: 'society', difficulty: 3, description: 'Михайло Драгоманов почав видавати перший український політичний журнал в еміграції.' },
  { id: 'koryfei-theatre', year: 1882, title: 'Театр корифеїв', category: 'culture', difficulty: 3, description: 'Марко Кропивницький зібрав першу професійну українську театральну трупу.' },
  { id: 'rurp-party', year: 1890, title: 'Перша українська політична партія', category: 'state', difficulty: 3, description: 'У Львові заснували Русько-українську радикальну партію Франка й Павлика.' },
  { id: 'kyiv-tram', year: 1892, title: 'Перший електричний трамвай', category: 'science', difficulty: 2, description: 'У Києві запустили перший електричний трамвай Російської імперії.' },
  { id: 'first-football-match', year: 1894, title: 'Перший футбольний матч у Львові', category: 'society', difficulty: 3, description: 'На крайовій виставці у Львові відбувся перший задокументований матч на українських землях.' },
  { id: 'hrushevsky-history', year: 1898, title: 'Перший том «Історії України-Руси»', category: 'science', difficulty: 2, description: 'Михайло Грушевський почав видавати фундаментальну історію українського народу.' },
  { id: 'rup-party', year: 1900, title: 'Революційна українська партія', category: 'state', difficulty: 3, description: 'У Харкові постала перша політична партія Наддніпрянщини.' },
  { id: 'kotliarevsky-monument', year: 1903, title: 'Пам’ятник Котляревському в Полтаві', category: 'culture', difficulty: 3, description: 'Відкриття пам’ятника зібрало весь цвіт українства з обох імперій.' },
  { id: 'khliborob-newspaper', year: 1905, title: 'Перша україномовна газета Наддніпрянщини', category: 'society', difficulty: 3, description: 'У Лубнах почав виходити «Хлібороб» — легальна газета українською мовою.' },
  { id: 'mechnikov-nobel', year: 1908, title: 'Нобелівська премія Іллі Мечникова', category: 'science', difficulty: 3, description: 'Уродженець Харківщини отримав Нобеля за дослідження імунітету.' },
  { id: 'lisova-pisnia', year: 1911, title: '«Лісова пісня» Лесі Українки', category: 'culture', difficulty: 3, description: 'Поетеса за кілька днів написала свою знамениту драму-феєрію.' },
  { id: 'nesterov-loop', year: 1913, title: 'Перша «мертва петля» Нестерова', category: 'science', difficulty: 3, description: 'Над київським аеродромом пілот уперше у світі виконав замкнену петлю в повітрі.' },
  { id: 'sikorsky-giant', year: 1913, title: 'Літак-гігант Ігоря Сікорського', category: 'science', difficulty: 3, description: 'Киянин Сікорський підняв у небо перший у світі чотиримоторний літак.' },

  // ——— Визвольні змагання та міжвоєнна доба ———
  { id: 'usus-legion', year: 1914, title: 'Легіон Українських січових стрільців', category: 'resistance', difficulty: 2, description: 'В австрійському війську створили перше українське національне формування.' },
  { id: 'black-square', year: 1915, title: '«Чорний квадрат» Малевича', category: 'culture', difficulty: 3, description: 'Художник київського походження показав найвідомішу картину авангарду.' },
  { id: 'shchedryk-premiere', year: 1916, title: 'Перше виконання «Щедрика»', category: 'culture', difficulty: 2, description: 'Хор університету в Києві вперше заспівав обробку Леонтовича — майбутній Carol of the Bells.' },
  { id: 'central-rada', year: 1917, title: 'Створення Української Центральної Ради', category: 'state', difficulty: 1, description: 'У Києві постав представницький орган, що очолив українську революцію.' },
  { id: 'unr-proclaimed', year: 1917, title: 'Проголошення УНР', category: 'state', difficulty: 2, description: 'Третій Універсал проголосив Українську Народну Республіку у федерації з Росією.' },
  { id: 'upr-independence', year: 1918, title: 'Проголошення незалежності УНР', category: 'state', difficulty: 1, description: 'Четвертий Універсал Центральної Ради проголосив Українську Народну Республіку самостійною.' },
  { id: 'kruty-battle', year: 1918, title: 'Бій під Крутами', category: 'resistance', difficulty: 2, description: 'Київські студенти й гімназисти затримали наступ більшовиків на столицю.' },
  { id: 'skoropadsky-hetmanate', year: 1918, title: 'Гетьманат Павла Скоропадського', category: 'state', difficulty: 3, description: 'Переворот встановив Українську Державу з гетьманом на чолі.' },
  { id: 'zunr-proclaimed', year: 1918, title: 'Проголошення ЗУНР', category: 'state', difficulty: 2, description: 'У Львові проголосили Західноукраїнську Народну Республіку.' },
  { id: 'academy-of-sciences', year: 1918, title: 'Заснування Академії наук України', category: 'science', difficulty: 2, description: 'У Києві створили національну академію, першим президентом став Володимир Вернадський.' },
  { id: 'act-of-unification', year: 1919, title: 'Акт Злуки', category: 'state', difficulty: 2, description: 'На Софійській площі проголосили об’єднання УНР і Західноукраїнської Народної Республіки.' },
  { id: 'warsaw-agreement', year: 1920, title: 'Варшавська угода', category: 'state', difficulty: 3, description: 'Петлюра й Пілсудський уклали союз проти більшовиків ціною Галичини.' },
  { id: 'riga-peace', year: 1921, title: 'Ризький мир', category: 'state', difficulty: 3, description: 'Польща й радянська Росія поділили українські землі, поховавши незалежність УНР.' },
  { id: 'ussr-founding', year: 1922, title: 'Утворення СРСР', category: 'state', difficulty: 2, description: 'УСРР стала однією з чотирьох республік-засновниць Радянського Союзу.' },
  { id: 'berezil-theatre', year: 1922, title: 'Театр «Березіль» Леся Курбаса', category: 'culture', difficulty: 3, description: 'У Києві постав найвпливовіший авангардний театр України.' },
  { id: 'ukrainization', year: 1923, title: 'Початок політики українізації', category: 'society', difficulty: 3, description: 'Більшовики тимчасово дозволили розвиток української мови й культури.' },
  { id: 'petliura-assassination', year: 1926, title: 'Вбивство Симона Петлюри', category: 'state', difficulty: 3, description: 'Головного отамана УНР застрелили в Парижі.' },
  { id: 'oun-founded', year: 1929, title: 'Створення ОУН', category: 'resistance', difficulty: 2, description: 'У Відні націоналістичні організації об’єдналися в ОУН на чолі з Коновальцем.' },
  { id: 'zemlia-film', year: 1930, title: 'Прем’єра фільму «Земля»', category: 'culture', difficulty: 2, description: 'Стрічка Олександра Довженка увійшла до найкращих фільмів світового кіно.' },
  { id: 'dniprohes-launch', year: 1932, title: 'Запуск Дніпрогесу', category: 'science', difficulty: 2, description: 'На Дніпрі запрацювала найбільша на той час гідроелектростанція Європи.' },
  { id: 'kharkiv-atom', year: 1932, title: 'Розщеплення атомного ядра в Харкові', category: 'science', difficulty: 3, description: 'Фізики УФТІ першими в СРСР розщепили ядро атома літію.' },
  { id: 'holodomor', year: 1933, title: 'Пік Голодомору', category: 'society', difficulty: 1, description: 'Штучний голод, організований радянською владою, забрав мільйони життів українців.' },
  { id: 'capital-kyiv', year: 1934, title: 'Перенесення столиці до Києва', category: 'state', difficulty: 2, description: 'Столицю радянської України перенесли з Харкова до Києва.' },
  { id: 'paton-institute', year: 1934, title: 'Інститут електрозварювання Патона', category: 'science', difficulty: 3, description: 'У Києві створили інститут, що зробив зварювання світовою наукою.' },
  { id: 'great-terror', year: 1937, title: 'Пік Великого терору', category: 'society', difficulty: 2, description: 'Масові репресії знищили тисячі українських митців, науковців і селян.' },
  { id: 'carpatho-ukraine', year: 1939, title: 'Проголошення Карпатської України', category: 'state', difficulty: 2, description: 'Закарпаття на один день стало незалежною державою з Волошиним на чолі.' },
  { id: 'western-ukraine-1939', year: 1939, title: 'Радянські війська в Західній Україні', category: 'state', difficulty: 2, description: 'Після пакту Молотова—Ріббентропа Галичину й Волинь приєднали до УРСР.' },
  { id: 'bukovyna-1940', year: 1940, title: 'Приєднання Північної Буковини', category: 'state', difficulty: 3, description: 'СРСР зайняв Буковину й Бессарабію, розширивши межі радянської України.' },
  { id: 'war-begins-1941', year: 1941, title: 'Початок німецько-радянської війни', category: 'society', difficulty: 1, description: 'Нацистська Німеччина напала на СРСР; Україна стала головним театром війни.' },
  { id: 'act-1941', year: 1941, title: 'Акт відновлення Української Держави', category: 'resistance', difficulty: 3, description: 'У Львові ОУН проголосила відновлення державності, за що нацисти ув’язнили її провід.' },
  { id: 'babyn-yar', year: 1941, title: 'Трагедія Бабиного Яру', category: 'society', difficulty: 2, description: 'Нацисти розстріляли в київському урочищі десятки тисяч людей, переважно євреїв.' },
  { id: 'upa-founded', year: 1942, title: 'Створення УПА', category: 'resistance', difficulty: 2, description: 'На Поліссі та Волині постала Українська повстанська армія.' },
  { id: 'kyiv-liberation', year: 1943, title: 'Визволення Києва від нацистів', category: 'resistance', difficulty: 2, description: 'Радянські війська повернули контроль над столицею України в ході Другої світової війни.' },
  { id: 'crimean-tatars-deportation', year: 1944, title: 'Депортація кримських татар', category: 'society', difficulty: 2, description: 'Радянська влада примусово виселила кримськотатарський народ із його батьківщини.' },
  { id: 'ukraine-liberated-1944', year: 1944, title: 'Вигнання нацистів з України', category: 'resistance', difficulty: 2, description: 'Восени радянські війська вийшли на всю тодішню територію УРСР.' },
  { id: 'ukraine-un-founder', year: 1945, title: 'Україна серед засновників ООН', category: 'state', difficulty: 2, description: 'Українська РСР стала однією з держав-засновниць Організації Об’єднаних Націй.' },
  { id: 'zakarpattia-1945', year: 1945, title: 'Приєднання Закарпаття до УРСР', category: 'society', difficulty: 3, description: 'За договором із Чехословаччиною Закарпаття увійшло до радянської України.' },
  { id: 'lviv-sobor-1946', year: 1946, title: 'Ліквідація УГКЦ радянською владою', category: 'society', difficulty: 3, description: 'Інспірований владою собор «возз’єднав» греко-католиків із московською церквою.' },
  { id: 'visla-operation', year: 1947, title: 'Операція «Вісла»', category: 'society', difficulty: 2, description: 'Польська влада примусово виселила українців із Лемківщини та Холмщини.' },

  // ——— Радянська доба ———
  { id: 'shukhevych-death', year: 1950, title: 'Загибель Романа Шухевича', category: 'resistance', difficulty: 3, description: 'Головнокомандувач УПА загинув у бою з військами МДБ під Львовом.' },
  { id: 'mesm-computer', year: 1951, title: 'Запуск ЕОМ «МЕСМ» у Києві', category: 'science', difficulty: 2, description: 'Команда Сергія Лебедєва створила першу електронну обчислювальну машину континентальної Європи.' },
  { id: 'waksman-nobel', year: 1952, title: 'Нобелівська премія Зельмана Ваксмана', category: 'science', difficulty: 3, description: 'Уродженець Вінниччини отримав Нобеля за відкриття стрептоміцину.' },
  { id: 'paton-bridge', year: 1953, title: 'Відкриття мосту Патона', category: 'science', difficulty: 3, description: 'У Києві запрацював найбільший у світі суцільнозварний міст.' },
  { id: 'crimea-transfer', year: 1954, title: 'Передача Криму до складу УРСР', category: 'state', difficulty: 3, description: 'Президія Верховної Ради СРСР передала Кримську область зі складу РРФСР до України.' },
  { id: 'sputnik-koroliov', year: 1957, title: 'Запуск першого супутника Землі', category: 'science', difficulty: 2, description: 'Космічну програму, що вивела «Супутник-1» на орбіту, очолював житомирянин Сергій Корольов.' },
  { id: 'bandera-assassination', year: 1959, title: 'Вбивство Степана Бандери', category: 'resistance', difficulty: 3, description: 'Агент КДБ убив провідника ОУН у Мюнхені.' },
  { id: 'kyiv-metro', year: 1960, title: 'Відкриття київського метро', category: 'science', difficulty: 2, description: 'Перша лінія метрополітену з’єднала вокзал із Дніпром.' },
  { id: 'two-hares-film', year: 1961, title: 'Прем’єра «За двома зайцями»', category: 'culture', difficulty: 3, description: 'Комедія з Олегом Борисовим і Маргаритою Криніциною стала культовою.' },
  { id: 'popovych-flight', year: 1962, title: 'Перший українець у космосі', category: 'science', difficulty: 3, description: 'Павло Попович із Київщини здійснив орбітальний політ на «Востоку-4».' },
  { id: 'cybernetics-institute', year: 1962, title: 'Інститут кібернетики в Києві', category: 'science', difficulty: 3, description: 'Віктор Глушков очолив головний центр радянської кібернетики.' },
  { id: 'shadows-premiere', year: 1965, title: 'Прем’єра «Тіней забутих предків»', category: 'culture', difficulty: 3, description: 'Фільм Сергія Параджанова став знаковим твором українського поетичного кіно.' },
  { id: 'dziuba-work', year: 1965, title: 'Праця Дзюби про русифікацію', category: 'society', difficulty: 3, description: '«Інтернаціоналізм чи русифікація?» стала маніфестом шістдесятників.' },
  { id: 'sobor-honchar', year: 1968, title: 'Роман «Собор» Олеся Гончара', category: 'culture', difficulty: 3, description: 'Роман про збереження духовної спадщини влада зустріла цькуванням.' },
  { id: 'space-welding', year: 1969, title: 'Перше зварювання в космосі', category: 'science', difficulty: 3, description: 'Апарат «Вулкан» Інституту Патона вперше зварював метал на орбіті.' },
  { id: 'chervona-ruta', year: 1970, title: '«Червона рута» Володимира Івасюка', category: 'culture', difficulty: 2, description: 'Пісня з Чернівців стала неофіційним гімном української естради.' },
  { id: 'arrests-1972', year: 1972, title: 'Хвиля арештів інтелігенції', category: 'society', difficulty: 3, description: 'КДБ ув’язнив Стуса, Чорновола, Світличного та десятки дисидентів.' },
  { id: 'dynamo-cup-winners-cup', year: 1975, title: 'Тріумф київського «Динамо» в Європі', category: 'society', difficulty: 3, description: 'Команда Валерія Лобановського першою в СРСР виграла Кубок володарів кубків УЄФА.' },
  { id: 'helsinki-group', year: 1976, title: 'Українська Гельсінська група', category: 'society', difficulty: 2, description: 'Правозахисники на чолі з Руденком почали відкрито захищати права людини.' },
  { id: 'ruslan-flight', year: 1982, title: 'Перший політ Ан-124 «Руслан»', category: 'science', difficulty: 3, description: 'Київські авіабудівники підняли в небо найбільший серійний літак світу.' },
  { id: 'perestroika', year: 1985, title: 'Початок перебудови', category: 'society', difficulty: 2, description: 'Реформи Горбачова відкрили шлях до гласності й національного відродження.' },
  { id: 'chornobyl-disaster', year: 1986, title: 'Аварія на Чорнобильській АЕС', category: 'society', difficulty: 1, description: 'Вибух четвертого реактора спричинив одну з найбільших техногенних катастроф у світі.' },
  { id: 'mriya-first-flight', year: 1988, title: 'Перший політ Ан-225 «Мрія»', category: 'science', difficulty: 2, description: 'У Києві злетів найбільший транспортний літак світу, збудований КБ Антонова.' },
  { id: 'lviv-rallies-1988', year: 1988, title: 'Перші масові мітинги у Львові', category: 'society', difficulty: 3, description: 'Тисячі людей вийшли на площі, вимагаючи демократії та статусу української мови.' },
  { id: 'rukh-founded', year: 1989, title: 'Створення Народного руху України', category: 'society', difficulty: 2, description: 'Установчий з’їзд Руху об’єднав опозицію та наблизив незалежність.' },

  // ——— Незалежна Україна ———
  { id: 'human-chain-1990', year: 1990, title: 'Живий ланцюг Злуки', category: 'society', difficulty: 2, description: 'Сотні тисяч людей узялися за руки від Києва до Львова в річницю Акту Злуки.' },
  { id: 'sovereignty-declaration', year: 1990, title: 'Декларація про державний суверенітет', category: 'state', difficulty: 2, description: 'Верховна Рада проголосила верховенство українських законів на території республіки.' },
  { id: 'revolution-on-granite', year: 1990, title: 'Революція на граніті', category: 'resistance', difficulty: 3, description: 'Студентське голодування на площі в Києві змусило радянський уряд піти на поступки.' },
  { id: 'independence-act', year: 1991, title: 'Відновлення незалежності України', category: 'state', difficulty: 1, description: 'Верховна Рада ухвалила Акт проголошення незалежності, підтверджений референдумом.' },
  { id: 'state-symbols', year: 1992, title: 'Затвердження прапора і тризуба', category: 'state', difficulty: 2, description: 'Парламент затвердив синьо-жовтий прапор і малий герб — тризуб Володимира.' },
  { id: 'hyperinflation-1993', year: 1993, title: 'Пік гіперінфляції карбованця', category: 'society', difficulty: 3, description: 'Ціни за рік зросли в понад сто разів — антирекорд у мирній Європі.' },
  { id: 'baiul-gold', year: 1994, title: 'Перше олімпійське золото України', category: 'society', difficulty: 2, description: 'Фігуристка Оксана Баюл виборола першу золоту медаль незалежної держави.' },
  { id: 'budapest-memorandum', year: 1994, title: 'Будапештський меморандум', category: 'state', difficulty: 2, description: 'Україна віддала ядерну зброю в обмін на запевнення про безпеку.' },
  { id: 'council-of-europe', year: 1995, title: 'Вступ до Ради Європи', category: 'state', difficulty: 3, description: 'Україна приєдналася до головної правозахисної організації континенту.' },
  { id: 'constitution-of-ukraine', year: 1996, title: 'Ухвалення Конституції України', category: 'state', difficulty: 1, description: 'Парламент затвердив Основний Закон незалежної української держави.' },
  { id: 'hryvnia-introduction', year: 1996, title: 'Запровадження гривні', category: 'society', difficulty: 2, description: 'Грошова реформа замінила купоно-карбованці на національну валюту — гривню.' },
  { id: 'vernadsky-station', year: 1996, title: 'Станція «Академік Вернадський»', category: 'science', difficulty: 3, description: 'Британія передала Україні антарктичну станцію «Фарадей».' },
  { id: 'kadeniuk-flight', year: 1997, title: 'Політ Леоніда Каденюка в космос', category: 'science', difficulty: 2, description: 'Перший космонавт незалежної України здійснив політ на борту шатла Columbia.' },
  { id: 'nato-charter', year: 1997, title: 'Хартія про партнерство з НАТО', category: 'state', difficulty: 3, description: 'У Мадриді підписали хартію про особливе партнерство України з альянсом.' },
  { id: 'okean-elzy-debut', year: 1998, title: 'Дебютний альбом «Океану Ельзи»', category: 'culture', difficulty: 3, description: 'Платівка «Там, де нас нема» відкрила головний рок-гурт країни.' },
  { id: 'sea-launch', year: 1999, title: 'Перший пуск «Морського старту»', category: 'science', difficulty: 3, description: 'Українська ракета «Зеніт-3SL» стартувала з плавучої платформи в океані.' },
  { id: 'chornobyl-shutdown', year: 2000, title: 'Зупинка Чорнобильської АЕС', category: 'society', difficulty: 2, description: 'Останній реактор станції остаточно вимкнули.' },
  { id: 'pope-visit', year: 2001, title: 'Візит Папи Івана Павла II', category: 'society', difficulty: 3, description: 'Понтифік відвідав Київ і Львів, зібравши мільйони вірян.' },
  { id: 'ponomariov-chess', year: 2002, title: 'Пономарьов — чемпіон світу з шахів', category: 'society', difficulty: 3, description: 'Вісімнадцятирічний українець став наймолодшим чемпіоном світу ФІДЕ.' },
  { id: 'tuzla-conflict', year: 2003, title: 'Конфлікт довкола Тузли', category: 'state', difficulty: 3, description: 'Російське будівництво дамби до української коси ледь не переросло в сутичку.' },
  { id: 'ruslana-eurovision', year: 2004, title: 'Перемога Руслани на Євробаченні', category: 'culture', difficulty: 2, description: '«Дикі танці» принесли Україні першу перемогу на конкурсі.' },
  { id: 'orange-revolution', year: 2004, title: 'Помаранчева революція', category: 'society', difficulty: 1, description: 'Масові мирні протести домоглися повторного голосування на президентських виборах.' },
  { id: 'shevchenko-ballon', year: 2004, title: '«Золотий м’яч» Андрія Шевченка', category: 'society', difficulty: 2, description: 'Форвард «Мілана» став третім українцем-володарем нагороди.' },
  { id: 'eurovision-kyiv', year: 2005, title: 'Євробачення вперше в Києві', category: 'culture', difficulty: 3, description: 'Україна вперше приймала пісенний конкурс Європи.' },
  { id: 'world-cup-2006', year: 2006, title: 'Збірна України в чвертьфіналі ЧС', category: 'society', difficulty: 2, description: 'У своєму дебютному мундіалі команда Блохіна дійшла до чвертьфіналу.' },
  { id: 'serduchka-eurovision', year: 2007, title: 'Срібло Вєрки Сердючки на Євробаченні', category: 'culture', difficulty: 3, description: '«Dancing Lasha Tumbai» стала одним із найвідоміших номерів конкурсу.' },
  { id: 'wto-membership', year: 2008, title: 'Вступ України до СОТ', category: 'state', difficulty: 3, description: 'Україна стала повноправним членом Світової організації торгівлі.' },
  { id: 'shakhtar-uefa', year: 2009, title: '«Шахтар» виграв Кубок УЄФА', category: 'society', difficulty: 2, description: 'Донецька команда здобула останній в історії Кубок УЄФА.' },
  { id: 'euro-2012', year: 2012, title: 'Чемпіонат Європи з футболу в Україні', category: 'society', difficulty: 2, description: 'Україна разом із Польщею прийняла фінальну частину Євро-2012.' },
  { id: 'euromaidan-start', year: 2013, title: 'Початок Євромайдану', category: 'resistance', difficulty: 1, description: 'Після відмови від угоди з ЄС кияни вийшли на Майдан Незалежності.' },
  { id: 'revolution-of-dignity', year: 2014, title: 'Революція Гідності', category: 'resistance', difficulty: 1, description: 'Протести на Майдані змінили політичний курс країни та стали символом боротьби за свободу.' },
  { id: 'crimea-occupation', year: 2014, title: 'Окупація Криму Росією', category: 'resistance', difficulty: 1, description: 'Російські війська захопили півострів, який Україна та світ визнають окупованим.' },
  { id: 'donbas-war', year: 2014, title: 'Початок війни на Донбасі', category: 'resistance', difficulty: 2, description: 'Підтримувані Росією бойовики захопили частину Донецької та Луганської областей.' },
  { id: 'eu-association', year: 2014, title: 'Угода про асоціацію з ЄС', category: 'state', difficulty: 2, description: 'Україна підписала угоду, заради якої стояв Майдан.' },
  { id: 'minsk-agreements', year: 2015, title: 'Мінські домовленості', category: 'state', difficulty: 3, description: 'У Мінську погодили план припинення вогню на Донбасі.' },
  { id: 'decommunization', year: 2015, title: 'Закони про декомунізацію', category: 'society', difficulty: 3, description: 'Україна почала прощатися з радянськими назвами й пам’ятниками.' },
  { id: 'jamala-eurovision', year: 2016, title: 'Перемога Джамали на Євробаченні', category: 'culture', difficulty: 2, description: 'Українська співачка перемогла з піснею «1944» про депортацію кримських татар.' },
  { id: 'chornobyl-arch', year: 2016, title: 'Нова арка над Чорнобильською АЕС', category: 'science', difficulty: 3, description: 'Над зруйнованим реактором насунули найбільшу рухому споруду світу.' },
  { id: 'eu-visa-free', year: 2017, title: 'Безвізовий режим з ЄС', category: 'society', difficulty: 2, description: 'Громадяни України з біометричними паспортами отримали право коротких безвізових подорожей.' },
  { id: 'tomos-autocephaly', year: 2019, title: 'Томос про автокефалію ПЦУ', category: 'state', difficulty: 2, description: 'Вселенський патріархат надав Православній церкві України грамоту про незалежність.' },
  { id: 'diia-app', year: 2020, title: 'Запуск застосунку «Дія»', category: 'science', difficulty: 2, description: 'Україна однією з перших у світі зрівняла цифрові документи з паперовими.' },
  { id: 'covid-ukraine', year: 2020, title: 'Початок пандемії COVID-19 в Україні', category: 'society', difficulty: 2, description: 'Перший підтверджений випадок коронавірусу змінив життя країни.' },
  { id: 'crimea-platform', year: 2021, title: 'Перший саміт Кримської платформи', category: 'state', difficulty: 3, description: 'Київ зібрав десятки держав для координації тиску щодо деокупації Криму.' },
  { id: 'full-scale-invasion', year: 2022, title: 'Повномасштабне вторгнення Росії', category: 'resistance', difficulty: 1, description: 'Україна розпочала загальнонаціональну оборону проти широкомасштабної російської агресії.' },
  { id: 'moskva-cruiser', year: 2022, title: 'Затоплення крейсера «Москва»', category: 'resistance', difficulty: 2, description: 'Українські ракети «Нептун» потопили флагман російського Чорноморського флоту.' },
  { id: 'kalush-eurovision', year: 2022, title: 'Перемога Kalush Orchestra на Євробаченні', category: 'culture', difficulty: 2, description: 'Гурт із піснею «Stefania» здобув для України третю перемогу на конкурсі.' },
  { id: 'eu-candidate-status', year: 2022, title: 'Статус кандидата на вступ до ЄС', category: 'state', difficulty: 2, description: 'Європейська рада надала Україні статус кандидата на членство в Європейському Союзі.' },
  { id: 'kherson-liberation', year: 2022, title: 'Звільнення Херсона', category: 'resistance', difficulty: 2, description: 'ЗСУ повернули єдиний обласний центр, захоплений після лютого 2022 року.' },
  { id: 'new-calendar', year: 2023, title: 'Перехід церкви на новий календар', category: 'society', difficulty: 3, description: 'ПЦУ перейшла на новоюліанський календар; Різдво — 25 грудня.' },
  { id: 'eu-negotiations', year: 2023, title: 'Рішення про переговори щодо вступу до ЄС', category: 'state', difficulty: 2, description: 'Європейська рада ухвалила відкрити переговори про членство України.' },
  { id: 'oscar-mariupol', year: 2024, title: '«Оскар» за «20 днів у Маріуполі»', category: 'culture', difficulty: 2, description: 'Фільм Мстислава Чернова приніс Україні першу премію «Оскар».' },
  { id: 'usyk-champion', year: 2024, title: 'Усик — абсолютний чемпіон світу', category: 'society', difficulty: 1, description: 'Олександр Усик першим у XXI столітті зібрав усі пояси надважкої ваги.' },
]);

const ids = new Set();
for (const event of EVENTS) {
  if (ids.has(event.id)) {
    throw new Error(`Duplicate event id: ${event.id}`);
  }
  if (!Number.isInteger(event.year)) {
    throw new Error(`Invalid year for event: ${event.id}`);
  }
  if (!CATEGORY_META[event.category]) {
    throw new Error(`Unknown category for event: ${event.id}`);
  }
  if (![1, 2, 3].includes(event.difficulty)) {
    throw new Error(`Invalid difficulty for event: ${event.id}`);
  }
  ids.add(event.id);
}
